 * Serving Flask app './ontobot/__init__.py'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.3:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 47
    @app.route('/op/checkpoint_1/taxowl_generate', methods=['POST'])
    ^
IndentationError: expected an indented block after function definition on line 44
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 48, in <module>
    @app.route('/op/checkpoint_1/taxowl_generate', methods=['POST'])
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\scaffold.py", line 449, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\scaffold.py", line 50, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\app.py", line 1361, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: get_taxo_download_local
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
127.0.0.1 - - [17/Apr/2023 15:36:19] "POST /op/checkpoint_1/taxowl_generate HTTP/1.1" 200 -
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
127.0.0.1 - - [17/Apr/2023 19:23:18] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2023 19:24:00] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 69
    //return Response.send_response(new_parsed_json)
    ^^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 71
    else:
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 68
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 70
    return Response.
                    ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 127
    class Response:
IndentationError: unexpected unindent
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 125
    def warn
            ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 125
    def warn()
              ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 74
    else:
IndentationError: expected an indented block after 'else' statement on line 71
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 74
    else:
IndentationError: expected an indented block after 'else' statement on line 71
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 73
    return Error.
                 ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 73
    return Error.next(err=warn_list, "warning")
                                              ^
SyntaxError: positional argument follows keyword argument
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 78
    return Error.next(err=, type="")
                          ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 78
    return Error.next(err=, type="error")
                          ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 79
    'list': 
          ^
SyntaxError: expression expected after dictionary key and ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 80
    ''
     ^
SyntaxError: ':' expected after dictionary key
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 80
    't'
      ^
SyntaxError: ':' expected after dictionary key
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 80
    'tc'
       ^
SyntaxError: ':' expected after dictionary key
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 80
    'tcwm'
         ^
SyntaxError: ':' expected after dictionary key
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 80
    'tcwm' : 
           ^
SyntaxError: expression expected after dictionary key and ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 87
    def get_taxonomy_owl(parsed_json):
IndentationError: expected an indented block after 'except' statement on line 83
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 85
    return Error.next(err=)
                          ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 3, in <module>
    from ontobot.services import taxonomy_service, op_service, populate_service
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\services\taxonomy_service.py", line 85
    return Error.next(err=, type="error")
                          ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 27
    if result['code']
                     ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 27
    if result['code'] == 
                         ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 27
    if result['code'] == 201
                            ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 31
    @app.route('/op/checkpoint_1/taxowl_generate/consistency', methods=['POST'])
IndentationError: expected an indented block after 'if' statement on line 27
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 33
    @app.route('/op/checkpoint_1/taxowl_generate/consistency', methods=['POST'])
IndentationError: expected an indented block after 'else' statement on line 29
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if 
       ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if r
        ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if result
             ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if result[]
              ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if result['']
                 ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if result['type']
                     ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 30
    if result['type'] == 'error'
                                ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 34
    @app.route('/op/checkpoint_1/taxowl_generate/consistency', methods=['POST'])
IndentationError: expected an indented block after 'if' statement on line 30
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 32
    el:
       ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 32
    elif:
        ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 32
    elif :
         ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 32
    elif result['type]:
                ^
SyntaxError: unterminated string literal (detected at line 32)
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 28
    return Response.send_response(msg=)
                                      ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 31
    return Error.send_taxonomy_warn(warn_list=)
                                              ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 31
    return Error.send_taxonomy_warn(warn_list=result[])
                                              ^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 33
    return Error.send_taxonomy_error(concept_list=)
                                                  ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 33
    return Error.send_taxonomy_error(concept_list=result[])
                                                  ^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 35
    return Error.
                 ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 116
    def server_err
                  ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 116
    def server_error
                    ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 116
    def server_error(msg)
                         ^
SyntaxError: expected ':'
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 2, in <module>
    from ontobot.model.output import Error, Response
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\model\output.py", line 120
    @staticmethod
    ^
IndentationError: expected an indented block after function definition on line 116
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
127.0.0.1 - - [17/Apr/2023 19:49:26] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2023 19:49:43] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2023 19:50:27] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2023 19:50:42] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\model\\output.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
127.0.0.1 - - [17/Apr/2023 19:52:16] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2023 19:52:29] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 56
    result = taxonomy_service.get_taxonomy_owl(request.)
                                                       ^
SyntaxError: invalid syntax
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 58
    return Error.send_something_went_wrong_error(result['msg'])
    ^^^^^^
IndentationError: expected an indented block after 'if' statement on line 57
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 60
    return Response.send_response(msg=result['msg'])
    ^^^^^^
IndentationError: expected an indented block after 'else' statement on line 59
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
127.0.0.1 - - [17/Apr/2023 19:59:11] "POST /onto/checkpoint_1/validate HTTP/1.1" 200 -
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 85, in <module>
    def get_taxo_download_local():
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\scaffold.py", line 449, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\scaffold.py", line 50, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\app.py", line 1361, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: get_taxo_download_local
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Asus\.virtualenvs\flask-server-AxbIE3V_\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\GitHub\Ontobot\ontobot-app\flask-server\ontobot\__init__.py", line 96
    @app.route('/op/checkpoint_1/op_generate', methods=['POST'])
IndentationError: expected an indented block after 'else' statement on line 92
 * Debugger is active!
 * Debugger PIN: 595-252-581
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
 * Detected change in 'C:\\GitHub\\Ontobot\\ontobot-app\\flask-server\\ontobot\\services\\taxonomy_service.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 792-081-341
